(defparameter *mm-per-inch* 25.4)
(defparameter *thick* 0.0373)
(defun mm-to-ft (mm)
  (/ mm (* *mm-per-inch* 12.0)))
(defun ft-to-mm (ft)
  (* 12.0 *mm-per-inch* ft))
(defparameter *ev-height-ft* 29000.0)
(defparameter *ev-height-mm* (ft-to-mm *ev-height-ft*))
(defun roll-thick (mm)
  (sqrt (- (* mm (/ *thick* pi)) (* 18.8 18.8) )))
